HERDING_GROUP = ['Australian Cattle Dog',
                 'Australian Shepherd',
                 'Bearded Collie',
                 'Beauceron',
                 'Belgian Malinois',
                 'Belgian Sheepdog',
                 'Belgian Tervuren',
                 'Bergamasco',
                 'Berger Picard',
                 'Border Collie',
                 'Bouvier des Flandres',
                 'Briard',
                 'Canaan Dog',
                 'Cardigan Welsh Corgi',
                 'Collie',
                 'Entlebucher Mountain Dog',
                 'Finnish Lapphund',
                 'German Shepherd Dog',
                 'Icelandic Sheepdog',
                 'Miniature American Shepherd',
                 'Norwegian Buhund',
                 'Old English Sheepdog',
                 'Pembroke Welsh Corgi',
                 'Polish Lowland Sheepdog',
                 'Puli',
                 'Pumi',
                 'Pyrenean Shepherd',
                 'Shetland Sheepdog',
                 'Spanish Water Dog',
                 'Swedish Vallhund']

SPORTING_GROUP_DESCRIPTION = "Naturally active and alert, Sporting dogs make likeable, well-rounded companions. Members of the Group include pointers, retrievers, setters and spaniels. Remarkable for their instincts in water and woods, many of these breeds actively continue to participate in hunting and other field activities. Potential owners of Sporting dogs need to realize that most require regular, invigorating exercise."

HERDING_GROUP_DESCRIPTION = "The Herding Group, created in 1983, is the newest AKC classification; its members were formerly members of the Working Group. All breeds share the fabulous ability to control the movement of other animals. A remarkable example is the low-set Corgi, perhaps one foot tall at the shoulders, that can drive a herd of cows many times its size to pasture by leaping and nipping at their heels. The vast majority of Herding dogs, as household pets, never cross paths with a farm animal. Nevertheless, pure instinct prompts many of these dogs to gently herd their owners, especially the children of the family. In general, these intelligent dogs make excellent companions and respond beautifully to training exercises."

HOUND_GROUP = ['Afghan Hound',
               'American English Coonhound',
               'American Foxhound',
               'Basenji',
               'Basset Hound',
               'Beagle',
               'Black and Tan Coonhound',
               'Bloodhound',
               'Bluetick Coonhound',
               'Borzoi',
               "Cirneco dell'Etna",
               'Dachshund',
               'English Foxhound',
               'Greyhound',
               'Harrier',
               'Ibizan Hound',
               'Irish Wolfhound',
               'Norwegian Elkhound',
               'Otterhound',
               'Petit Basset Griffon Vendeen',
               'Pharaoh Hound',
               'Plott',
               'Portuguese Podengo Pequeno',
               'Redbone Coonhound',
               'Rhodesian Ridgeback',
               'Saluki',
               'Scottish Deerhound',
               'Sloughi',
               'Treeing Walker Coonhound',
               'Whippet']


HOUND_GROUP_DESCRIPTION = "Most hounds share the common ancestral trait of being used for hunting. Some use acute scenting powers to follow a trail. Others demonstrate a phenomenal gift of stamina as they relentlessly run down quarry. Beyond this, however, generalizations about hounds are hard to come by, since the Group encompasses quite a diverse lot. There are Pharaoh Hounds, Norwegian Elkhounds, Afghans and Beagles, among others. Some hounds share the distinct ability to produce a unique sound known as baying. You'd best sample this sound before you decide to get a hound of your own to be sure it's your cup of tea."

NON_SPORTING_GROUP = ['American Eskimo Dog',
                      'Bichon Frise',
                      'Boston Terrier',
                      'Bulldog',
                      'Chinese Shar-Pei',
                      'Chow Chow',
                      'Coton de Tulear',
                      'Dalmatian',
                      'Finnish Spitz',
                      'French Bulldog',
                      'Keeshond',
                      'Lhasa Apso',
                      'Lowchen',
                      'Norwegian Lundehund',
                      'Poodle',
                      'Schipperke',
                      'Shiba Inu',
                      'Tibetan Spaniel',
                      'Tibetan Terrier',
                      'Xoloitzcuintli']

NON_SPORTING_GROUP_DESCRIPTION = "Non-sporting dogs are a diverse group. Here are sturdy animals with as different personalities and appearances as the Chow Chow, Dalmatian, French Bulldog, and Keeshond. Talk about differences in size, coat, and visage! Some, like the Schipperke and Tibetan Spaniel are uncommon sights in the average neighborhood. Others, however, like the Poodle and Lhasa Apso, have quite a large following. The breeds in the Non-Sporting Group are a varied collection in terms of size, coat, personality and overall appearance."

TERRIER_GROUP = ['Airedale Terrier',
                 'American Hairless Terrier',
                 'American Staffordshire Terrier',
                 'Australian Terrier',
                 'Bedlington Terrier',
                 'Border Terrier',
                 'Bull Terrier',
                 'Cairn Terrier',
                 'Cesky Terrier',
                 'Dandie Dinmont Terrier',
                 'Glen of Imaal Terrier',
                 'Irish Terrier',
                 'Kerry Blue Terrier',
                 'Lakeland Terrier',
                 'Manchester Terrier',
                 'Miniature Bull Terrier',
                 'Miniature Schnauzer',
                 'Norfolk Terrier',
                 'Norwich Terrier',
                 'Parson Russell Terrier',
                 'Rat Terrier',
                 'Russell Terrier',
                 'Scottish Terrier',
                 'Sealyham Terrier',
                 'Skye Terrier',
                 'Smooth Fox Terrier',
                 'Soft Coated Wheaten Terrier',
                 'Staffordshire Bull Terrier',
                 'Welsh Terrier',
                 'West Highland White Terrier',
                 'Wire Fox Terrier']

TERRIER_GROUP_DESCRIPTION = "People familiar with this Group invariably comment on the distinctive terrier personality. These are feisty, energetic dogs whose sizes range from fairly small, as in the Norfolk, Cairn or West Highland White Terrier, to the grand Airedale Terrier. Terriers typically have little tolerance for other animals, including other dogs. Their ancestors were bred to hunt and kill vermin. Many continue to project the attitude that they're always eager for a spirited argument. Most terriers have wiry coats that require special grooming known as stripping in order to maintain a characteristic appearance. In general, they make engaging pets, but require owners with the determination to match their dogs' lively characters."

TOY_GROUP = ['Affenpinscher',
             'Brussels Griffon',
             'Cavalier King Charles Spaniel',
             'Chihuahua',
             'Chinese Crested',
             'English Toy Spaniel',
             'Havanese',
             'Italian Greyhound',
             'Japanese Chin',
             'Maltese',
             'Manchester Terrier',
             'Miniature Pinscher',
             'Papillon',
             'Pekingese',
             'Pomeranian',
             'Poodle',
             'Pug',
             'Shih Tzu',
             'Silky Terrier',
             'Toy Fox Terrier',
             'Yorkshire Terrier']

TOY_GROUP_DESCRIPTION = "The diminutive size and winsome expressions of Toy dogs illustrate the main function of this Group: to embody sheer delight. Don't let their tiny stature fool you, though - - many Toys are tough as nails. If you haven't yet experienced the barking of an angry Chihuahua, for example, well, just wait. Toy dogs will always be popular with city dwellers and people without much living space. They make ideal apartment dogs and terrific lap warmers on nippy nights. (Incidentally, small breeds may be found in every Group, not just the Toy Group. We advise everyone to seriously consider getting a small breed, when appropriate, if for no other reason than to minimize some of the problems inherent in canines such as shedding, creating messes and cost of care. And training aside, it's still easier to control a ten-pound dog than it is one ten times that size.)"

WORKING_GROUP = ['Akita',
                 'Alaskan Malamute',
                 'Anatolian Shepherd Dog',
                 'Bernese Mountain Dog',
                 'Black Russian Terrier',
                 'Boerboel',
                 'Boxer',
                 'Bullmastiff',
                 'Cane Corso',
                 'Chinook',
                 'Doberman Pinscher',
                 'Dogue de Bordeaux',
                 'German Pinscher',
                 'Giant Schnauzer',
                 'Great Dane',
                 'Great Pyrenees',
                 'Greater Swiss Mountain Dog',
                 'Komondor',
                 'Kuvasz',
                 'Leonberger',
                 'Mastiff',
                 'Neapolitan Mastiff',
                 'Newfoundland',
                 'Portuguese Water Dog',
                 'Rottweiler',
                 'Samoyed',
                 'Siberian Husky',
                 'Standard Schnauzer',
                 'Tibetan Mastiff',
                 'St. Bernard']

WORKING_GROUP_DESCRIPTION = "Dogs of the Working Group were bred to perform such jobs as guarding property, pulling sleds and performing water rescues. They have been invaluable assets to man throughout the ages. The Doberman Pinscher, Siberian Husky and Great Dane are included in this Group, to name just a few. Quick to learn, these intelligent, capable animals make solid companions. Their considerable dimensions and strength alone, however, make many working dogs unsuitable as pets for average families. And again, by virtue of their size alone, these dogs must be properly trained."

FOUNDATION_STOCK_SERVICE = ['American Leopard Hound',
                            'Appenzeller Sennenhunde',
                            'Azawakh',
                            'Barbet',
                            'Basset Fauve de Bretagne',
                            'Belgian Laekenois',
                            'Biewer Terrier',
                            'Bolognese',
                            'Bracco Italiano',
                            'Braque du Bourbonnais',
                            'Braque Francais Pyrenean',
                            'Broholmer',
                            'Catahoula Leopard Dog',
                            'Caucasian Shepherd Dog',
                            'Central Asian Shepherd Dog',
                            'Czechoslovakian Vlcak',
                            'Danish-Swedish Farmdog',
                            'Deutscher Wachtelhund',
                            'Dogo Argentino',
                            'Drentsche Patrijshond',
                            'Drever',
                            'Dutch Shepherd',
                            'Estrela Mountain Dog',
                            'Eurasier',
                            'French Spaniel',
                            'German Longhaired Pointer',
                            'German Spitz',
                            'Grand Basset Griffon Vendeen',
                            'Hamiltonstovare',
                            'Hokkaido',
                            'Hovawart',
                            'Jagdterrier',
                            'Jindo',
                            'Kai Ken',
                            'Karelian Bear Dog',
                            'Kishu Ken',
                            'Kromfohrlander',
                            'Lancashire Heeler',
                            'Mudi',
                            'Nederlandse Kooikerhondje',
                            'Norrbottenspets',
                            'Perro de Presa Canario',
                            'Peruvian Inca Orchid',
                            'Portuguese Podengo',
                            'Portuguese Pointer',
                            'Portuguese Sheepdog',
                            'Pudelpointer',
                            'Pyrenean Mastiff',
                            'Rafeiro do Alentejo',
                            'Russian Toy',
                            'Russian Tsvetnaya Bolonka',
                            'Schapendoes',
                            'Shikoku',
                            'Slovensky Cuvac',
                            'Slovensky Kopov',
                            'Small Munsterlander Pointer',
                            'Spanish Mastiff',
                            'Stabyhoun',
                            'Swedish Lapphund',
                            'Teddy Roosevelt Terrier',
                            'Thai Ridgeback',
                            'Tornjak',
                            'Tosa',
                            'Transylvanian Hound',
                            'Treeing Tennessee Brindle',
                            'Working Kelpie']

FOUNDATION_STOCK_SERVICE_DESCRIPTION = "Each of the following breeds has been accepted for recording in the AKC Foundation Stock Service. The AKC provides this service to allow these purebred breeds to continue to develop while providing them with the security of a reliable and reputable avenue to maintain their records. FSS breeds are not eligible for AKC registration. Most of the FSS breeds are approved to compete in AKC Companion Events. Contact information is available for a majority of the Foundation Stock Service breeds. The AKC does not recommend one club over another. None of the clubs are affiliated with the AKC at this time (except for the Coonhound national breed clubs)."
